### ISSUE TITLE
How to contribute to this project?

### ISSUE THREAD

**Issue by kenji-miyake** [platisd/clang-tidy-pr-comments#17]
Hello, thank you for developing this project!
Although I just started to take a look at this, it looks so nice. :smile: 

So I'd like to contribute to this project and I believe I can contribute mainly 3 points.
How should I contribute? Could I send PRs for these?

### 1. Release Management

By adding CI scripts like [this](https://github.com/kenji-miyake/clang-tidy-pr-comments/commits/add-release-ci), if I push a tag,
![image](https://user-images.githubusercontent.com/31987104/153720763-bbb923ce-7e3e-4a73-aa63-311ad4d34df2.png)

this CI will run,
https://github.com/kenji-miyake/clang-tidy-pr-comments/runs/5168564498?check_suite_focus=true

and a new release is prepared,
![image](https://user-images.githubusercontent.com/31987104/153720770-a08606a2-2d2e-49aa-ab17-5cefc9d50efd.png)

and after I publish it, the major version tag is created as well.
https://github.com/kenji-miyake/clang-tidy-pr-comments/runs/5168578795?check_suite_focus=true
![image](https://user-images.githubusercontent.com/31987104/153720792-43efe7e3-6976-4a95-b8d6-c31719d8ec43.png)

Why doing so is here: 
https://github.com/actions/toolkit/blob/2f164000dcd42fb08287824a3bc3030dbed33687/docs/action-versioning.md

### 2. Other CI scripts

It seems some files are not properly formatted.
![image](https://user-images.githubusercontent.com/31987104/153722643-88fa227a-1206-460b-9268-c309fbb9c4eb.png)

By installing [pre-commit.ci](https://pre-commit.ci/) and other tools, this can be improved and it will reduce your maintenance cost.

Please see this project for more details: https://github.com/autowarefoundation/autoware-github-actions/

### 3. Bug investigations/fixes

While I'm testing this action, it seems I caught a bug. I can investigate the cause and fix it.
https://github.com/kenji-miyake/autoware.universe/runs/5168447074?check_suite_focus=true
![image](https://user-images.githubusercontent.com/31987104/153722787-f502dbeb-d184-4236-9e7d-7cd2cb1b6a78.png)

-> `clang_tidy_fixes` should be under the checked-out workspace?

**Comment by oleg-derevenetz** [comment]
Hi @platisd

> even though I haven't yet fully understood the last point

Since this action is executed in Docker container, it has its own `/tmp`, not the system `/tmp`. `fixes.yml` should be created somewhere in the `$HOME`, because it's mounted inside the Docker image, while system `/tmp` does not. This is not a bug in this action, but just in the caller's workflow.

**Comment by kenji-miyake** [comment]
@platisd Thank you, I'll send PRs and explain more details. Let's discuss there.

@oleg-derevenetz Thank you for your explanation!
Yes, you are right, only a few directories will be mounted. After I copied the file under the workspace, it worked.
![image](https://user-images.githubusercontent.com/31987104/153741024-176bdd27-aa1b-4e6b-a116-a4313385d6cb.png)

This was due to my lack of understanding, but I feel it's nice to write it in the README.md, because somebody would try to avoid "Redownload" as I did.

```yaml
jobs:
  clang-tidy-pr-comments:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download analysis results
        run: |
          gh run download ${{ github.event.workflow_run.id }} -D /tmp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: set-variables
        run: |
          echo ::set-output name=pr-id::"$(cat /tmp/clang-tidy-result/pr-id.txt)"
          echo ::set-output name=pr-head-repo::"$(cat /tmp/clang-tidy-result/pr-head-repo.txt)"
          echo ::set-output name=pr-head-ref::"$(cat /tmp/clang-tidy-result/pr-head-ref.txt)"
      - name: Check out PR head
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.set-variables.outputs.pr-head-repo }}
          ref: ${{ steps.set-variables.outputs.pr-head-ref }}
          persist-credentials: false

      - name: Copy fixes.yaml to access from Docker Container Action
        run: |
          cp /tmp/clang-tidy-result/fixes.yaml fixes.yaml

      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@1.1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: fixes.yaml
          pull_request_id: ${{ steps.set-variables.outputs.pr-id }}
```

**Comment by kenji-miyake** [comment]
By the way, are you interested in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)?

If we follow this, we can automatically generate the changelog.
For example, please see this one: https://github.com/tier4/autoware.universe/pull/11#issue-1128590125
It can also be used for GitHub Releases.

To enforce it, we can use [amannn/action-semantic-pull-request/](https://github.com/amannn/action-semantic-pull-request/).

If you are interested, I can send a PR.

**Comment by kenji-miyake** [comment]
I sent PRs #18, #19, and #20.
Please take a look at them when you have the time.
If you have any questions, I can explain them in more detail.

**Comment by kenji-miyake** [comment]
@platisd Thank you for merging PRs!
If possible, could I create an issue for my question or can I ask it here?

I'd like to ask why no warnings were found with this PR.

- PR: https://github.com/kenji-miyake/autoware.universe/pull/2
- Artifacts: https://github.com/kenji-miyake/autoware.universe/actions/runs/1836303338
- Result: https://github.com/kenji-miyake/autoware.universe/runs/5173061895?check_suite_focus=true#step:8:9

The following diagnostic is in `fixes.yaml.

```yaml
  - DiagnosticName:  modernize-use-using
    DiagnosticMessage:
      Message:         'use ''using'' instead of ''typedef'''
      FilePath:        '/__w/autoware.universe/autoware.universe/common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp'
      FileOffset:      1328
      Replacements:
        - FilePath:        '/__w/autoware.universe/autoware.universe/common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp'
          Offset:          1328
          Length:          16
          ReplacementText: 'using B = double'
```

Should I run `run-clang-tidy` instead of `clang-tidy` [here](https://github.com/autowarefoundation/autoware-github-actions/blob/ad0cbd2801815fc268b8ce26200305419c053ee7/clang-tidy/action.yaml#L105)? :thinking:
