### ISSUE TITLE
Bug: warnings not correctly recognized

### ISSUE THREAD

**Issue by rhaschke** [platisd/clang-tidy-pr-comments#32]
In [this build](https://github.com/rhaschke/industrial_ci/actions/runs/3289506187/jobs/5421180080), clang-tidy found some warnings (and fixes):
```
Run cat /home/runner/work/industrial_ci/industrial_ci/.work/clang-tidy-fixes.yml
Diagnostics:
- DiagnosticName: readability-identifier-naming
  FileOffset: 26
  FilePath: /home/runner/work/industrial_ci/industrial_ci/.work/target_ws/src/test_clang_tidy/src/test_clang_tidy.cpp
  Message: invalid case style for variable 'a'
  Replacements:
  - {FilePath: /home/runner/work/industrial_ci/industrial_ci/.work/target_ws/src/test_clang_tidy/src/test_clang_tidy.cpp,
    Length: 1, Offset: 26, ReplacementText: A}
MainSourceFile: ''
```
but the action reports:
`No warnings found in files changed in this pull request`
