### ISSUE TITLE
multiline code-suggestions

### ISSUE THREAD

**Issue by jellespijker** [platisd/clang-tidy-pr-comments#37]
Hi,

Might be that this request is not relevant or that the problem lies somewhere else. We ([UltiMaker Cura](https://github.com/Ultimaker/Cura)) recently start using your GitHub action, for our custom-made linting tool. We wrote a small Python module which performs linting on a `json` file which contains definition for 3D printers used in Cura. Since we have a lot of community contributions we want provide the community contributors with some automatic feedback on their PR's

The output of this linting tool follows the same scheme as `clang-tidy`. See the example below:

<details>

```yaml
Diagnostics:
-   DiagnosticMessage:
        FileOffset: 238
        FilePath: /home/jspijker/cura_wp/Cura/resources/extruders/koonovo_kn5_extruder_1.def.json
        Message: 'Overriding machine_nozzle_offset_x with the same value (0.0) as defined in parent definition: fdmextruder'
        Replacements:
        -   FilePath: /home/jspijker/cura_wp/Cura/resources/extruders/koonovo_kn5_extruder_1.def.json
            Length: 52
            Offset: 246
            ReplacementText: ''
    DiagnosticName: diagnostic-definition-redundant-override
    Level: Warning
-   DiagnosticMessage:
        FileOffset: 299
        FilePath: /home/jspijker/cura_wp/Cura/resources/extruders/koonovo_kn5_extruder_1.def.json
        Message: 'Overriding machine_nozzle_offset_y with the same value (0.0) as defined in parent definition: fdmextruder'
        Replacements:
        -   FilePath: /home/jspijker/cura_wp/Cura/resources/extruders/koonovo_kn5_extruder_1.def.json
            Length: 52
            Offset: 307
            ReplacementText: ''
    DiagnosticName: diagnostic-definition-redundant-override
    Level: Warning
-   DiagnosticMessage:
        FileOffset: 360
        FilePath: /home/jspijker/cura_wp/Cura/resources/extruders/koonovo_kn5_extruder_1.def.json
        Message: 'Overriding machine_nozzle_size with the same value (0.4) as defined in parent definition: fdmextruder'
        Replacements:
        -   FilePath: /home/jspijker/cura_wp/Cura/resources/extruders/koonovo_kn5_extruder_1.def.json
            Length: 48
            Offset: 368
            ReplacementText: ''
```

</details>

However some of our suggested fixes are fixes over multiple lines, which this Action seems to have some trouble with, at least when we use it in conjunction with our custom **printer-linter**. It could be that the fixes suggested by `clang-tidy` are always confined to a single line so it isn't an issue for normal usage. But it would really help us if this action handles multi line `suggestion` comments

![image](https://user-images.githubusercontent.com/8535734/204763298-27ef9664-fa72-4d1d-b27f-0dcd0525d961.png)
The suggestion in the image would result in an ill-formed json

**Comment by platisd** [comment]
Great to see this workflow being used in a product I use! :}

I will try to take a look later today.

**Comment by platisd** [comment]
I can reproduce the problem with C++ and `clang-tidy` [here](https://github.com/platisd/cpp-command-parser/pull/1#discussion_r1036426636). The suggestion in that case is actually wrong, as in it does not compile. :scream: 

The `yaml` file looks like this:

```yaml
Diagnostics:
- BuildDirectory: /home/dimitris/projects/cpp-command-parser/build
  DiagnosticMessage:
    FileOffset: 3064
    FilePath: /home/dimitris/projects/cpp-command-parser/include/CommandParser.h
    Message: constructors that are callable with a single argument must be marked
      explicit to avoid unintentional implicit conversions
    Replacements:
    - FilePath: /home/dimitris/projects/cpp-command-parser/include/CommandParser.h
      Length: 0
      Offset: 3064
      ReplacementText: 'explicit '
  DiagnosticName: google-explicit-constructor
  Level: Warning
- BuildDirectory: /home/dimitris/projects/cpp-command-parser/build
  DiagnosticMessage:
    FileOffset: 7386
    FilePath: /home/dimitris/projects/cpp-command-parser/include/CommandParser.h
    Message: do not use 'else' after 'return'
    Ranges:
    - FileOffset: 7386
      FilePath: /home/dimitris/projects/cpp-command-parser/include/CommandParser.h
      Length: 4
    Replacements:
    - FilePath: /home/dimitris/projects/cpp-command-parser/include/CommandParser.h
      Length: 246
      Offset: 7386
      ReplacementText: "if (containsType<std::vector<std::string>, Args...>()) {\n\
        \            return std::numeric_limits<std::size_t>::max();\n        } else\
        \ {\n            // Some other line\n            // Some other line\n    \
        \        return sizeof...(Args);\n        }"
  DiagnosticName: readability-else-after-return
  Level: Warning
MainSourceFile: ''
```

I have included a single-line fix for reference. It seems like `clang-tidy` produces this `Ranges` field when it requires a multi-line fix.
I will try to fix this nonetheless for clang-tidy and hopefully it will also work for your use case? :crossed_fingers:

**Comment by jellespijker** [comment]
thx, I will mimic the `Ranges` output on our side. That would atleast make it compliant with their scheme.

If you manage to fix it in the action it should work.

**Comment by platisd** [comment]
The `Ranges` part was a red herring, it's not needed/relevant. It should work fine without it. I may have something very soon.

**Comment by platisd** [comment]
@jellespijker could you please try `platisd/clang-tidy-pr-comments@fix_suggestions_for_multiline_comments` and tell me if it now works as intended?

**Comment by jellespijker** [comment]
That was a quick fix, I will try to plan some time in for this tomorrow afternoon.

**Comment by jellespijker** [comment]
Great!, We now have multiline code-suggestions: https://github.com/Ultimaker/Cura/pull/13940#pullrequestreview-1202211526

![image](https://user-images.githubusercontent.com/8535734/205261827-e8a59fbb-804c-4e93-bc4b-79b10746c132.png)

But It also suggest a change over two lines for a single line change. Although the end result would still be correct in this case 
![image](https://user-images.githubusercontent.com/8535734/205262054-d9dce02b-16e0-42ca-9da9-272df386b347.png)

I also noticed that there is also an extra space introduced.

The diagnostic results.yml looks like this in the case of this PR:
```yaml
Diagnostics:
-   DiagnosticMessage:
        FileOffset: 5213
        FilePath: /home/jspijker/cura_wp/Cura/resources/definitions/super_printer.def.json
        Message: 'Overriding support_use_towers with the same value (False) as defined in parent definition: ultimaker'
        Replacements:
        -   FilePath: /home/jspijker/cura_wp/Cura/resources/definitions/super_printer.def.json
            Length: 69
            Offset: 5229
            ReplacementText: ''
    DiagnosticName: diagnostic-definition-redundant-override
    Level: Warning
-   DiagnosticMessage:
        FileOffset: 5741
        FilePath: /home/jspijker/cura_wp/Cura/resources/definitions/super_printer.def.json
        Message: 'Overriding bridge_skin_density with the same value (80) as defined in parent definition: ultimaker'
        Replacements:
        -   FilePath: /home/jspijker/cura_wp/Cura/resources/definitions/super_printer.def.json
            Length: 49
            Offset: 5749
            ReplacementText: ''
    DiagnosticName: diagnostic-definition-redundant-override
    Level: Warning
```

**Comment by platisd** [comment]
Thanks for the feedback @jellespijker 

> But It also suggest a change over two lines for a single line change

I looked into this and while I couldn't reproduce it with C++ and `clang-tidy` I think I know why. 

```yaml
-   FilePath: /home/jspijker/cura_wp/Cura/resources/definitions/super_printer.def.json
Length: 69
Offset: 5229
ReplacementText: ''
```

The above configuration requires the replacement of `69` characters starting from [L103](https://github.com/Ultimaker/Cura/blob/334307165c461510fa3a1180b3991aa7d5a653df/resources/definitions/super_printer.def.json#L103) and  `"support_use_towers"`.
If I counted correctly, this goes all the way down to L106 just before `"infill_wipe_dist"` begins. So I tend to think that it's not an issue of the workflow.

> I also noticed that there is also an extra space introduced.

:thinking: I noticed it as well in some of my tests. I am not currently sure whether this is a workflow bug or not. I will look more tomorrow. :+1:
