### ISSUE TITLE
Error appending replacements in multi-line comments

### ISSUE THREAD

**Issue by florian-kuebler** [platisd/clang-tidy-pr-comments#41]
With [#38](https://github.com/platisd/clang-tidy-pr-comments/pull/38), suggestions including multiple replacements where tried to be tackled. However, right now, replacements text is only concatenated and the length is being summed, which is a bit too simple, resulting in potentially unusable comments.

Consider the following example:
![Screenshot 2022-12-12 at 16 50 26](https://user-images.githubusercontent.com/2725914/207091872-5a9fb6a3-fb55-456f-b1c4-f94b19ac17eb.png)

```
Diagnostics:
- BuildDirectory: /home/runner/work/orbitprofiler/orbitprofiler/build/src/DataViews
  DiagnosticMessage:
    FileOffset: 1269
    FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
    Message: invalid case style for local variable 'resultingColumns_'
    Replacements:
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1269
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1292
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1335
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1420
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1503
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1581
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1663
      ReplacementText: resulting_columns
    - FilePath: /home/runner/work/orbitprofiler/orbitprofiler/src/DataViews/CallstackDataView.cpp
      Length: 17
      Offset: 1762
      ReplacementText: resulting_columns
  DiagnosticName: readability-identifier-naming
  Level: Warning
MainSourceFile: ''
```

**Comment by platisd** [comment]
:scream: Crap, I'll take a look. Thanks for reporting it.

**Comment by platisd** [comment]
I haven't had time to fix this yet, but I was thinking of trying out the following logic.
Let's take this as an example of a good use-case for merging comments:

```yaml
    Replacements:
    - FilePath: /home/me/projects/cpp-command-parser/include/CommandParser.h
      Length: 5
      Offset: 8851
      ReplacementText: ''
    - FilePath: /home/me/projects/cpp-command-parser/include/CommandParser.h
      Length: 47
      Offset: 8856
      ReplacementText: "            return sizeof...(Args);\n       "
```

The main difference compared to the one you posted above is that they are "consecutive", i.e. if you sum the length and the offset, you end up in the next offset (or the next offset -1 in another case).

So I am hoping that we can distinguish between the two cases and support both? :thinking: 

What do you mean by "atomic" suggestion comments btw?
