### ISSUE TITLE
The logic of searching for consecutive replacements is broken

### ISSUE THREAD

**Issue by oleg-derevenetz** [platisd/clang-tidy-pr-comments#46]
The current logic here:

https://github.com/platisd/clang-tidy-pr-comments/blob/3fae50b904c5c9fd507b9fab1cb916055a392e8c/run_action.py#L218-L233

is problematic. Consider the following `fixes.yml`:

```yaml
Diagnostics:
- BuildDirectory: /home/runner/work/fheroes2/fheroes2/build/src/fheroes2
  DiagnosticMessage:
    FileOffset: 7837
    FilePath: /home/runner/work/fheroes2/fheroes2/src/fheroes2/kingdom/kingdom.cpp
    Message: return type 'const EventsDate' (aka 'const list<EventDate>') is 'const'-qualified
      at the top level, which may reduce code readability without improving const
      correctness
    Ranges:
    - FileOffset: 7837
      FilePath: /home/runner/work/fheroes2/fheroes2/src/fheroes2/kingdom/kingdom.cpp
      Length: 5
    Replacements:
    - FilePath: /home/runner/work/fheroes2/fheroes2/src/fheroes2/kingdom/kingdom.cpp
      Length: 6
      Offset: 7837
      ReplacementText: ''
    - FilePath: /home/runner/work/fheroes2/fheroes2/src/fheroes2/kingdom/kingdom.h
      Length: 6
      Offset: 4838
      ReplacementText: ''
  DiagnosticName: readability-const-return-type
  Level: Warning
MainSourceFile: ''
```

First of all, these replacements are for different files with different `FilePath`s in each replacement, but this is not taken into account when checking for continuity. Second, even though these replacements are not consecutive, they are still considered as such, because `7837 + 6` is not less than `4838 - 1`.
